# Add a line between prompts
add_newline = true

# Change character to show in place of >
[character]
success_symbol = "[Δ](bold yellow)"
error_symbol = "[Δ](bold red)"

# Disable package module
[package]
disabled = true

[directory]
style = "bold purple"

# Disable battery
[battery]
disabled = true

# Languages Configuration #
[golang]
symbol = " "

# Hostname (for SSH)
[hostname]
disabled = false
format = "[$hostname]($style) "
style = "bold italic yellow"

# Git configuration #
[git_branch]
symbol = " "
truncation_symbol = ""

[git_commit]
commit_hash_length = 7
tag_symbol = " "

[git_status]
conflicted = " "
ahead = " "
behind = " "
diverged = " "
up_to_date = " "
untracked = " "
stashed = " "
modified = " "
staged = '[+\($count\)](green)'
renamed = " "
deleted = " "
